all_additives = ['Curcuma (turmeric)',
 'Riboflavin (Vitamin B2)',
 "Riboflavin-5'-Phosphate",
 'Tartrazine (FD&C Yellow 5)',
 'Chrysoine resorcinol',
 'Quinoline Yellow',
 'Fast Yellow AB',
 'Riboflavin-5-Sodium Phosphate',
 'Yellow 2G',
 'Sunset Yellow FCF (Orange Yellow S)',
 'Amylase',
 'Invertase',
 'Lysozyme',
 'Orange GGN',
 'Cochineal; Carminic acid; Carmines',
 'Polydextrose',
 'Polyvinylpyrrolidone',
 'Polyvinylpolypyrrolidone',
 'Citrus Red 2',
 'Carmoisine; Azorubine',
 'Amaranth; FD&C Red 2',
 'Ponceau 4R; Cochineal Red A, Brilliant Scarlet 4R',
 'Ponceau SX; Scarlet GN',
 'Ponceau 6R',
 'Erythrosine (FD&C Red 3)',
 'Red 2G',
 'Allura Red AC (FD&C Red 40)',
 'Indanthrene blue RS',
 'Patent Blue V',
 'Indigo carmine; FD&C Blue 2',
 'Brilliant Blue FCF (FD&C Blue 1)',
 'Chlorophylls and chlorophyllins',
 'Oxidised starch',
 'Copper complexes of chlorophylls and chlorophyllins',
 'Monostarch phosphate',
 'Distarch phosphate',
 'Phosphated distarch phosphate',
 'Acetylated distarch phosphate',
 'Green S',
 'Acetylated starch',
 'Acetylated distarch adipate',
 'Fast Green FCF (FD&C Green 3)',
 'Hydroxyl propyl starch',
 'Hydroxyl propyl distarch phosphate',
 'Starch sodium octenyl succinate',
 'Acetylated oxidised starch',
 'Triethyl citrate',
 'Plain caramel',
 'Caustic sulphite caramel',
 'Ammonia caramel',
 'Sulphite ammonia caramel',
 'Black PN; Brilliant Black BN',
 'Ethanol',
 'Glyceryl triacetate, triacetin',
 'Propylene glycol',
 'Vegetable carbon',
 'Brown FK',
 'Brown HT',
 'Carotenes',
 'Annatto; Bixin; Norbixin',
 'Paprika extract; Capsanthian; Capsorubin',
 'Lycopene',
 "Beta-apo-8' carotenal (C30)",
 "Ethyl ester of beta-apo-8'-carotenic acid (C 30)",
 'Lutein',
 'Canthaxanthin',
 'Beetroot Red; Betanin',
 'Anthocyanins',
 'Calcium carbonate',
 'Titanium dioxide',
 'Iron oxides and hydroxides',
 'Aluminium',
 'Silver',
 'Gold',
 'Pigment Rubine; Lithol Rubine BK',
 'Tannin',
 'Sorbic acid',
 'Sodium sorbate',
 'Potassium sorbate',
 'Calcium sorbate',
 'Benzoic acid',
 'Sodium benzoate',
 'Potassium benzoate',
 'Calcium benzoate',
 'Ethyl p-hydroxybenzoate',
 'Sodium ethyl p-hydroxybenzoate',
 'Propyl p-hydroxybenzoate',
 'Sodium propyl p-hydroxybenzoate',
 'Methyl p-hydroxybenzoate',
 'Sodium methyl p-hydroxybenzoate',
 'Sulphur dioxide',
 'Sodium sulphite',
 'Sodium hydrogen sulphite',
 'Sodium metabisuiphite',
 'Potassium metabisulphite',
 'Calcium sulphite',
 'Calcium hydrogen sulphite',
 'Potassium hydrogen sulphite',
 'Biphenyl; diphenyl',
 'Orthophenyl phenol',
 'Sodium orthophenyl phenol',
 'Thiabendazole',
 'Nisin',
 'Natamycin',
 'Formic acid',
 'Sodium formate',
 'Calcium formate',
 'Hexamethylene tetramine',
 'Dimethyl dicarbonate',
 'Potassium nitrite',
 'Sodium nitrite',
 'Sodium nitrate',
 'Potassium nitrate',
 'Acetic acid',
 'Potassium acetate',
 'Sodium acetate; Sodium diacetate',
 'Calcium acetate',
 'Ammonium acetate',
 'Lactic acid',
 'Propionic acid',
 'Sodium propionate',
 'Calcium propionate',
 'Potassium propionate',
 'Boric acid',
 'Sodium tetraborate; borax',
 'Carbon dioxide',
 'Malic acid',
 'Fumaric acid',
 'Ascorbic acid',
 'Sodium ascorbate',
 'Calcium ascorbate',
 'Potassium ascorbate',
 'Fatty acid esters of ascorbic acid',
 'Tocopherols',
 'Alpha-tocopherol',
 'Gamma-tocopherol',
 'Delta-tocopherol',
 'Propyl gallate',
 'Octyl gallate',
 'Dodecyl gallate',
 'Erythorbic acid',
 'Sodium erythorbate',
 'Erythorbic acid',
 'Sodium erythorbate',
 'Tert-ButylHydroQuinone (TBHQ)',
 'Butylated hydroxyanisole (BHA)',
 'Butylated hydroxytoluene (BHT)',
 'Lecithins',
 'Sodium lactate',
 'Potassium lactate',
 'Calcium lactate',
 'Ammonium lactate',
 'Magnesium lactate',
 'Citric acid',
 'Sodium citrates',
 'Potassium citrates',
 'Calcium citrates',
 'Tartaric acid',
 'Sodium tartrates',
 'Potassium tartrates',
 'Sodium potassium tartrate',
 'Phosphoric acid',
 'Sodium phosphates',
 'Potassium phosphates',
 'Calcium phosphates',
 'Magnesium phosphates',
 'Sodium malates',
 'Potassium malate',
 'Calcium malate',
 'Metatartaric acid',
 'Calcium tartrate',
 'Adipic acid',
 'Sodium adipate',
 'Potassium adipate',
 'Succinic acid',
 'Heptonolactone',
 'Niacin',
 'Triammonium citrate',
 'Ammonium ferric citrates',
 'Calcium disodium EDTA',
 'Alginic acid',
 'Sodium alginate',
 'Potassium alginate',
 'Ammonium alginate',
 'Calcium alginate',
 'Propane-1,2-diol alginate',
 'Agar',
 'Carrageenan',
 'Processed eucheuma seaweed',
 'Locust bean gum; carob gum',
 'Guar gum',
 'Tragacanth',
 'Acacia gum; gum arabic',
 'Xanthan gum',
 'Karaya gum',
 'Tara gum',
 'Gellan gum',
 'Sorbitol; Sorbitol syrup',
 'Mannitol',
 'Glycerol',
 'Konjac',
 'Polyoxyethylene stearate',
 'Polyoxyethylene (40) stearate',
 'Polysorbate 20',
 'Polysorbate 80',
 'Polysorbate 40',
 'Polysorbate 60',
 'Polysorbate 65',
 'Pectins',
 'Gelatine',
 'Ammonium phosphatides',
 'Sucrose acetate isobutyrate',
 'Glycerol esters of wood rosins',
 'Diphosphates',
 'Triphosphates',
 'Polyphosphates',
 'Beta-cyclodextrin',
 'Cellulose',
 'Methyl cellulose',
 'Hydroxypropyl cellulose',
 'Hydroxypropyl methyl cellulose',
 'Ethyl methyl cellulose',
 'Carboxy methyl cellulose',
 'Sodium carboxy methyl cellulose',
 'Croscarmellose',
 'Sodium caseinate',
 'Fatty acids salts',
 'Magnesium salts of fatty acids',
 'Mono- and diglycerides of fatty acids',
 'Fatty acid esters of glycerol',
 'Lactic acid esters of mono- and diglycerides of fatty acids',
 'Citric acid esters of mono- and diglycerides of fatty acids',
 'Tartaric acid esters of mono- and diglycerides of fatty acids',
 'Mono- and diacetyltartaric acid esters of mono- and diglycerides of fatty acids',
 'Mixed acetic and tartaric acid esters of mono- and diglycerides of fatty acids',
 'Sucrose esters of fatty acids',
 'Sucroglycerides',
 'Polyglycerol esters of fatty acids',
 'Polyglycerol polyricinoleate',
 'Propylene glycol esters of fatty acids',
 'Lactylated fatty acid esters of glycerol and propane',
 'Thermally oxidised soya bean oil interacted with mono and diglycerides of fatty acids',
 'Dioctyl sodium sulphosuccinate',
 'Sodium stearoyl-2-lactylate',
 'Calcium stearoyl-2-lactylate',
 'Stearyl tartrate',
 'Sorbitan monostearate',
 'Sorbitan tristearate',
 'Sorbitan monolaurate',
 'Sorbitan monooleate',
 'Sorbitan monopalmitate Sorbitan monopalmitate',
 'Sodium carbonates',
 'Potassium carbonate',
 'Ammonium carbonate',
 'Magnesium carbonate',
 'Hydrochloric acid',
 'Potassium chloride',
 'Calcium chloride',
 'Ammonium chloride',
 'Magnesium chloride',
 'Stannous chloride',
 'Sulfuric acid',
 'Sodium sulfate',
 'Potassium sulfate',
 'Calcium sulfate',
 'Ammonium sulfate',
 'Magnesium sulphate',
 'Copper sulphate',
 'Aluminium sulphate',
 'Aluminium sodium sulfate',
 'Aluminium potassium sulfate',
 'Aluminium ammonium sulfate',
 'Sodium hydroxide',
 'Potassium hydroxide',
 'Calcium hydroxide',
 'Ammonium hydroxide',
 'Magnesium hydroxide',
 'Calcium oxide',
 'Magnesium oxide',
 'Sodium ferrocyanide',
 'Potassium ferrocyanide',
 'Calcium ferrocyanide',
 'Dicalcium diphosphate',
 'Sodium aluminium phosphate',
 'Bone phosphate',
 'Calcium polyphosphates',
 'Ammonium polyphosphates',
 'Silicon dioxide',
 'Calcium silicate',
 'Magnesium silicate',
 'Talc',
 'Sodium aluminium silicate',
 'Potassium aluminium silicate',
 'Aluminium calcium silicate',
 'Bentonite',
 'Aluminium silicate, kaolin',
 'Fatty acids',
 'Gluconic acid',
 'Glucono delta lactone',
 'Sodium gluconate',
 'Potassium gluconate',
 'Calcium gluconate',
 'Ferrous gluconate',
 'Ferrous lactate',
 'Glutamic acid',
 'Monosodium glutamate',
 'Monopotassium glutamate',
 'Calcium diglutamate',
 'Monoammonium glutamate',
 'Magnesium diglutamate',
 'Guanylic acid',
 'Disodium guanylate',
 'Dipotassium guanylate',
 'Calcium guanylate',
 'Inosinic acid',
 'Disodium inosinate',
 'Dipotassium inosinate',
 'Calcium inosinate',
 "Calcium 5'-ribonucleotides",
 "Disodium 5'-ribonucleotides",
 'Maltol',
 'Ethyl maltol',
 'Glycine and its sodium salt',
 'Zinc acetate',
 'Spiramycins',
 'Tylosin',
 'Dimethylpolysiloxane',
 'Beeswax',
 'Candelilla wax',
 'Carnauba wax',
 'Shellac',
 'Microcrystalline wax',
 'Refined microcrystalline wax',
 'Montan acid esters',
 'Lanolin',
 'Oxidised polyethylene wax',
 'L-cysteine',
 'L-Cystin',
 'Potassium bromate',
 'Chlorine',
 'Chlorine dioxide',
 'Carbamide',
 'Benzoyl peroxide',
 'Nitrogen',
 'Nitrous oxide',
 'Argon',
 'Helium',
 'Nitrogen',
 'Nitrous oxide',
 'Butane',
 'Iso-butane',
 'Propane',
 'Oxygen',
 'Hydrogen',
 'Acesulphane potassium',
 'Aspartame',
 'Cyclamic acid and its Na and Ca salts',
 'lsomalt',
 'Saccharin and its Na, K and Ca salts',
 'Sucralose',
 'Thaumatin',
 'Neohesperidine DC',
 'Maltitol; Maltitol syrup',
 'Lactitol',
 'Xylitol',
 'Quillaia extract',
 'RED 40',
 'RED 40 LAKE',
 ]